"""
main.py — Groundhog REST API Server (FastAPI)

This is the ONLY process that imports and calls cognee directly (via memory.py).
All other services (dashboard, MCP server) must call these HTTP endpoints.

Endpoints:
  POST   /remember              Ingest a run
  POST   /check-config          Pre-flight Guard
  POST   /query                 Free-form memory query
  GET    /find-file             Artifact lookup by description
  GET    /lineage/{run_id}      Full decision/config chain for a run
  POST   /improve               Trigger graph enrichment
  POST   /forget                Remove stale data
  POST   /promote               Promote node to shared dataset
  GET    /orphans               Untracked files + broken artifact references
  GET    /health                Server + Cognee health check

OpenAPI schema: GET /openapi.json  (auto-generated by FastAPI)
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Optional

import cognee
from cognee import search, SearchType
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

load_dotenv()

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("groundhog.api")

# ---------------------------------------------------------------------------
# Cognee configuration (must happen before any cognee call)
# ---------------------------------------------------------------------------
# The real, multi-provider configuration lives in llm_setup.configure_cognee().
# _CONFIG holds what was actually applied, so /health can report it truthfully.
from llm_setup import configure_cognee

_CONFIG: Dict[str, Any] = {}


def _configure_cognee():
    """Configure Cognee's LLM + embeddings via the real setters (groq/gemini/aimlapi)."""
    global _CONFIG
    _CONFIG = configure_cognee()
    # Cognee's own pipeline tracing — observability into how memory was built
    # (plan §4.5, the "@observe" beat). Best-effort; never fatal.
    try:
        if os.getenv("GROUNDHOG_TRACING", "true").strip().lower() in {"1", "true", "yes"}:
            cognee.enable_tracing()
            logger.info("Cognee pipeline tracing enabled")
    except Exception as e:
        logger.warning("Could not enable cognee tracing: %s", e)


# ---------------------------------------------------------------------------
# Run counter for auto-improve trigger
# ---------------------------------------------------------------------------
_run_counter = 0
IMPROVE_EVERY_N = int(os.getenv("IMPROVE_EVERY_N_RUNS", "10"))

# ---------------------------------------------------------------------------
# Artifact registry (in-memory, populated by remember_run calls)
# ---------------------------------------------------------------------------
# Maps file_path -> {"result_id": ..., "artifact_type": ..., "description": ...}
_artifact_registry: Dict[str, Dict[str, Any]] = {}


# ---------------------------------------------------------------------------
# Lifespan (startup / shutdown)
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Configure Cognee and start file watcher on startup; clean up on shutdown."""
    _configure_cognee()
    # Initialize Cognee (creates SQLite + Kuzu DBs if not present)
    # IMPORTANT: cognee.prune.prune_system() defaults to graph=True, vector=True,
    # i.e. it WIPES the graph + vector store. The old code called it on every
    # startup labelled "non-destructive init ping" — it was the opposite, and
    # made the memory forget everything on each restart. Cognee initialises its
    # stores lazily on the first add()/cognify(), so no init ping is needed.
    # A clean wipe is now strictly opt-in via GROUNDHOG_RESET_ON_START=true.
    if os.getenv("GROUNDHOG_RESET_ON_START", "false").strip().lower() in {"1", "true", "yes"}:
        logger.warning("GROUNDHOG_RESET_ON_START set — wiping graph + vector store")
        try:
            await cognee.prune.prune_data()
            await cognee.prune.prune_system(graph=True, vector=True, metadata=True)
        except Exception as e:
            logger.warning("Reset-on-start prune failed: %s", e)

    # Start file watcher in background thread
    watch_dir = os.getenv("WATCHED_DIR", "./watched_runs")
    loop = asyncio.get_event_loop()
    try:
        from watcher import start_watcher
        start_watcher(watch_dir, loop, dataset_name="main_dataset")
        logger.info("File watcher started on: %s", os.path.abspath(watch_dir))
    except Exception as e:
        logger.warning("File watcher failed to start: %s", e)

    yield  # Server is running

    # Shutdown
    try:
        from watcher import stop_watcher
        stop_watcher()
    except Exception:
        pass


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Groundhog — ML Experiment Memory API",
    description=(
        "Data/memory layer for ML experiment reproducibility. "
        "Built on Cognee (graph memory) + Groq LLM. "
        "All graph operations go through this API — no other service should import cognee directly."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# CORS — permissive for local dev (dashboard runs on different port)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Pydantic request / response models (this IS the API contract)
# ---------------------------------------------------------------------------

class RememberRequest(BaseModel):
    """Full run document for ingestion."""
    config_params: Dict[str, Any] = Field(..., description="Hyperparameter dict")
    result_metrics: Dict[str, Any] = Field(default_factory=dict, description="Metric name → value")
    status: str = Field(default="completed", description="completed | aborted | failed")
    rationale: str = Field(default="", description="Researcher's free-text note for this run")
    experiment_name: str = Field(default="unnamed", description="Experiment container name")
    experiment_description: str = Field(default="", description="What this experiment is testing")
    owner: str = Field(default="unknown", description="Researcher or team name")
    thread_name: str = Field(default="default", description="Research thread this run belongs to")
    hypothesis: str = Field(default="", description="Hypothesis being tested")
    dataset_name_label: str = Field(default="unknown", description="Human-readable dataset label")
    dataset_version: str = Field(default="v1")
    preprocessing_notes: str = Field(default="")
    split_rationale: str = Field(default="")
    quality_issues: str = Field(default="")
    gpu_hours: Optional[float] = None
    wall_clock_seconds: Optional[float] = None
    output_dir: Optional[str] = Field(default=None, description="Directory to scan for artifacts")
    git_commit: str = Field(default="unknown")
    derived_from_config_hash: Optional[str] = Field(default=None)
    dataset: str = Field(default="main_dataset", description="Cognee dataset name for storage")
    session_id: Optional[str] = Field(
        default=None,
        description=(
            "If set, this is a private/exploratory write into cognee's session cache "
            "instead of the permanent graph (native session_id mechanism). Promote it "
            "later via POST /promote with the same session_id."
        ),
    )


class RememberResponse(BaseModel):
    node_id: str
    config_hash: str
    config_summary: str
    result_summary: str
    dataset_name: str
    artifact_paths: List[str]
    elapsed_seconds: float
    improved: bool = False
    node_set: Optional[List[str]] = None
    session_id: Optional[str] = None


class CheckConfigRequest(BaseModel):
    config_params: Dict[str, Any] = Field(..., description="Hyperparameter dict to check")
    dataset: str = Field(default="main_dataset")


class CheckConfigResponse(BaseModel):
    already_tried: bool
    match_type: str = Field(..., description="exact | similar | none")
    config_hash: str
    prior_result: Optional[Dict[str, Any]] = None
    similarity_score: Optional[float] = None


class QueryRequest(BaseModel):
    question: str = Field(..., description="Natural language question")
    dataset: Optional[str] = Field(default=None, description="Restrict to this dataset or None for all")
    node_name: Optional[List[str]] = Field(
        default=None,
        description="Scope to specific node_set tags, e.g. ['experiment:resnet_sweep']",
    )


class QueryResponse(BaseModel):
    answer: str
    sources: List[str]
    result_count: int
    dataset: Optional[str] = None


class AgentFindingRequest(BaseModel):
    """Subagent write-back into the shared graph (blackboard architecture, Section 7)."""
    agent_type: str = Field(..., description="e.g. config_proposer | triage | dataset_steward | literature | report")
    experiment_name: str = Field(..., description="Experiment this finding belongs to")
    content: str = Field(..., description="The finding/suggestion text, in the agent's own words")
    dataset: str = Field(default="main_dataset")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Structured extras (severity, config, etc.)")


class AgentFindingResponse(BaseModel):
    status: str
    agent_type: str
    experiment_name: str
    node_set: Optional[List[str]] = None
    finding_id: Optional[str] = None
    error: Optional[str] = None


class FindFileResponse(BaseModel):
    file_path: str
    artifact_id: str
    exists_on_disk: bool
    description: str
    artifact_type: str


class ImproveRequest(BaseModel):
    dataset_name: str = Field(default="main_dataset")


class ImproveResponse(BaseModel):
    status: str
    dataset: str
    message: Optional[str] = None
    error: Optional[str] = None


class ForgetRequest(BaseModel):
    dataset_name: str
    criteria: Dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Keys: delete_dataset (bool), status (str), max_wall_clock_seconds (float)"
        ),
    )


class ForgetResponse(BaseModel):
    status: str
    dataset: str
    deleted_count: int
    criteria: Dict[str, Any]
    note: Optional[str] = None
    error: Optional[str] = None


class PromoteRequest(BaseModel):
    to_dataset: str = Field(default="main_dataset")
    session_id: str = Field(
        ...,
        description=(
            "The session_id used in a prior POST /remember call. "
            "Promotes that session into to_dataset via cognee.improve(session_ids=[...])."
        ),
    )


class PromoteResponse(BaseModel):
    status: str
    mode: Optional[str] = None
    to_dataset: Optional[str] = None
    session_id: Optional[str] = None
    error: Optional[str] = None


class ArtifactInfo(BaseModel):
    file_path: str
    size_bytes: int
    artifact_type: str
    result_id: Optional[str] = None


class OrphansResponse(BaseModel):
    untracked_files: List[ArtifactInfo]
    broken_references: List[ArtifactInfo]
    total_untracked_size_bytes: int
    total_broken_size_bytes: int
    untracked_count: int
    broken_count: int


class HealthResponse(BaseModel):
    status: str
    cognee_version: str
    storage_backend: str
    llm_provider: str
    embedding_provider: str


class ErrorResponse(BaseModel):
    error: str
    detail: str


# ---------------------------------------------------------------------------
# Helper — structured error
# ---------------------------------------------------------------------------

def _error(status_code: int, error: str, detail: str):
    raise HTTPException(
        status_code=status_code,
        detail={"error": error, "detail": detail},
    )


# ---------------------------------------------------------------------------
# POST /remember
# ---------------------------------------------------------------------------

@app.post("/remember", response_model=RememberResponse, tags=["Core"])
async def remember(req: RememberRequest):
    """
    Ingest a full ML run document into the memory graph.

    Returns node IDs and config_hash immediately so the caller can build
    lineage links without another round-trip.
    """
    global _run_counter

    import run_index
    from memory import remember_run

    try:
        run_data = req.model_dump(exclude={"dataset", "session_id"})
        result = await remember_run(run_data, dataset_name=req.dataset, session_id=req.session_id)

        # Register artifacts in the in-memory registry AND the persistent index
        artifact_dicts = result.get("artifacts", [])
        for art in artifact_dicts:
            fpath = art["file_path"]
            _artifact_registry[fpath] = {
                "result_id": result["node_id"],
                "artifact_type": art.get("artifact_type", _infer_artifact_type(fpath)),
                "description": art.get("description", f"Auto-indexed artifact from run {result['node_id'][:12]}"),
                "exists_on_disk": os.path.exists(fpath),
            }
        run_index.record_artifacts(artifact_dicts)

        # Deterministic, restart-safe structured record for /runs and /lineage
        run_index.record_run({
            "run_id": result["node_id"],
            "config_hash": result["config_hash"],
            "experiment": req.experiment_name,
            "thread": req.thread_name,
            "config": req.config_params,
            "metrics": req.result_metrics,
            "status": req.status,
            "rationale": req.rationale,
            "gpu_hours": req.gpu_hours,
            "wall_clock_seconds": req.wall_clock_seconds,
            "git_commit": req.git_commit,
            "config_summary": result["config_summary"],
            "result_summary": result["result_summary"],
            "derived_from_config_hash": req.derived_from_config_hash,
            "artifact_paths": result.get("artifact_paths", []),
        })

        _run_counter += 1
        improved = False
        if _run_counter % IMPROVE_EVERY_N == 0:
            logger.info("Auto-triggering improve_memory (run_counter=%d)", _run_counter)
            asyncio.create_task(_auto_improve(req.dataset))
            improved = True

        return RememberResponse(**result, improved=improved)
    except Exception as e:
        logger.exception("remember() failed")
        _error(500, "ingestion_failed", str(e))


async def _auto_improve(dataset_name: str):
    from memory import improve_memory
    try:
        await improve_memory(dataset_name)
        logger.info("Auto-improve completed for dataset=%s", dataset_name)
    except Exception as e:
        logger.error("Auto-improve failed: %s", e)


def _infer_artifact_type(path: str) -> str:
    ext = os.path.splitext(path)[1].lower()
    mapping = {
        ".pt": "checkpoint", ".pth": "checkpoint", ".ckpt": "checkpoint",
        ".png": "plot", ".jpg": "plot", ".pdf": "plot", ".svg": "plot",
        ".log": "log", ".txt": "log",
        ".json": "eval_report", ".csv": "eval_report",
    }
    return mapping.get(ext, "other")


# ---------------------------------------------------------------------------
# POST /check-config
# ---------------------------------------------------------------------------

@app.post("/check-config", response_model=CheckConfigResponse, tags=["Core"])
async def check_config(req: CheckConfigRequest):
    """
    Pre-flight Guard: has this exact config been tried before?

    Returns exact hash match or semantic similarity match, plus prior result.
    Use this before launching a training run to avoid wasted compute.
    """
    from memory import check_config as _check_config
    try:
        result = await _check_config(req.config_params, dataset_name=req.dataset)
        return CheckConfigResponse(**result)
    except Exception as e:
        logger.exception("check_config() failed")
        _error(500, "check_config_failed", str(e))


# ---------------------------------------------------------------------------
# POST /query
# ---------------------------------------------------------------------------

@app.post("/query", response_model=QueryResponse, tags=["Core"])
async def query(req: QueryRequest):
    """
    Free-form natural language query against the memory graph.

    Works for positive AND negative results — ask "which runs failed?" and
    the graph will surface failed run nodes.
    """
    from memory import query_memory
    try:
        result = await query_memory(req.question, dataset_name=req.dataset, node_name=req.node_name)
        return QueryResponse(**result)
    except Exception as e:
        logger.exception("query_memory() failed")
        _error(500, "query_failed", str(e))


# ---------------------------------------------------------------------------
# POST /agent-finding
# ---------------------------------------------------------------------------

@app.post("/agent-finding", response_model=AgentFindingResponse, tags=["Core"])
async def agent_finding(req: AgentFindingRequest):
    """
    Subagent write-back into the shared graph.

    This is what makes the blackboard architecture (plan Section 7) real:
    a subagent's finding becomes a graph node other subagents (or a human,
    via POST /query) can recall() later — not just a row in a private table
    only that one agent's own UI can see.
    """
    import run_index
    from memory import remember_agent_finding
    try:
        result = await remember_agent_finding(
            agent_type=req.agent_type,
            experiment_name=req.experiment_name,
            content=req.content,
            dataset_name=req.dataset,
            metadata=req.metadata,
        )
        # Also index it deterministically so the dashboard can list findings
        # without asking the LLM to re-emit them as JSON. Dedup per agent+
        # experiment so re-running agents surface ONE current card, not a pile.
        # Triage is per-run, so its dedup key includes the run_id when present.
        run_id = (req.metadata or {}).get("run_id")
        dedup_key = f"{req.agent_type}:{req.experiment_name}"
        if req.agent_type == "triage" and run_id:
            dedup_key = f"triage:{req.experiment_name}:{run_id}"
        indexed = run_index.record_finding(
            {
                "agent_type": req.agent_type,
                "experiment": req.experiment_name,
                "content": req.content,
                "metadata": req.metadata,
                "severity": (req.metadata or {}).get("severity"),
            },
            dedup_key=dedup_key,
        )
        payload = dict(result)
        payload["finding_id"] = indexed["id"]
        return AgentFindingResponse(**payload)
    except Exception as e:
        logger.exception("remember_agent_finding() failed")
        _error(500, "agent_finding_failed", str(e))


# ---------------------------------------------------------------------------
# GET /runs  and  GET /agent-findings  (deterministic, index-backed)
# ---------------------------------------------------------------------------

@app.get("/runs", tags=["Core"])
async def list_runs(
    experiment: Optional[str] = Query(default=None),
    status: Optional[str] = Query(default=None),
    limit: int = Query(default=200),
):
    """
    Deterministic run listing straight from the structured index.

    Cognee stays the semantic memory; exact "list my runs" is served from the
    index instead of asking the LLM to hallucinate a JSON array.
    """
    import run_index
    return run_index.list_runs(experiment=experiment, status=status, limit=limit)


@app.get("/agent-findings", tags=["Core"])
async def list_agent_findings(
    experiment: Optional[str] = Query(default=None),
    limit: int = Query(default=200),
    include_dismissed: bool = Query(default=False),
):
    """Deterministic agent-finding listing from the structured index."""
    import run_index
    return run_index.list_findings(
        experiment=experiment, limit=limit, include_dismissed=include_dismissed
    )


@app.post("/agent-findings/{finding_id}/dismiss", tags=["Core"])
async def dismiss_agent_finding(finding_id: str):
    """Persistently dismiss an agent finding (survives restart)."""
    import run_index
    found = run_index.dismiss_finding(finding_id)
    if not found:
        raise HTTPException(
            status_code=404,
            detail={"error": "finding_not_found", "detail": finding_id},
        )
    return {"status": "dismissed", "id": finding_id}


# ---------------------------------------------------------------------------
# GET /find-file
# ---------------------------------------------------------------------------

@app.get("/find-file", response_model=FindFileResponse, tags=["Artifacts"])
async def find_file(description: str = Query(..., description="Text description of the artifact to find")):
    """
    Find an artifact file by semantic description.

    Searches the registered artifact registry and the memory graph.
    Returns the file path, artifact ID, and whether the file still exists.
    """
    # Check the persistent artifact index (survives restart) with token overlap
    import run_index
    from memory import _rough_similarity
    candidates = {a["file_path"]: a for a in run_index.list_artifacts()}
    for fpath, info in _artifact_registry.items():
        candidates.setdefault(fpath, {"file_path": fpath, **info})

    best_score = 0.0
    best_fpath = None
    for fpath, info in candidates.items():
        score = _rough_similarity(description, info.get("description", ""))
        if score > best_score:
            best_score = score
            best_fpath = fpath

    if best_fpath and best_score > 0.1:
        info = candidates[best_fpath]
        return FindFileResponse(
            file_path=best_fpath,
            artifact_id=best_fpath,
            exists_on_disk=os.path.exists(best_fpath),
            description=info.get("description", ""),
            artifact_type=info.get("artifact_type", "other"),
        )

    # Fall back to graph query
    from memory import query_memory
    result = await query_memory(f"Find artifact file: {description}")
    if result.get("sources"):
        src = result["sources"][0]
        return FindFileResponse(
            file_path=str(src),
            artifact_id=str(src),
            exists_on_disk=os.path.exists(str(src)),
            description=result.get("answer", "")[:200],
            artifact_type="other",
        )

    raise HTTPException(
        status_code=404,
        detail={"error": "artifact_not_found", "detail": f"No artifact matching: {description}"},
    )


# ---------------------------------------------------------------------------
# GET /lineage/{run_id}
# ---------------------------------------------------------------------------

@app.get("/lineage/{run_id}", tags=["Provenance"])
async def lineage(run_id: str):
    """
    Return the full decision / hypothesis / config chain for a run.

    run_id can be a config_hash or any node ID returned by /remember.
    """
    import run_index
    from memory import query_memory

    # Deterministic structural chain from the index: walk derived_from links.
    chain: List[Dict[str, Any]] = []
    seen = set()
    cur = run_index.get_run(run_id)
    while cur and cur.get("run_id") not in seen:
        seen.add(cur.get("run_id"))
        chain.append({
            "run_id": cur.get("run_id"),
            "experiment": cur.get("experiment"),
            "config_summary": cur.get("config_summary"),
            "status": cur.get("status"),
            "metrics": cur.get("metrics"),
            "derived_from_config_hash": cur.get("derived_from_config_hash"),
        })
        parent_hash = cur.get("derived_from_config_hash")
        cur = run_index.get_run(parent_hash) if parent_hash and parent_hash != "none" else None

    try:
        result = await query_memory(
            f"What is the full lineage, decision chain, and config history for run {run_id}?"
        )
        narrative = result.get("answer", "No lineage found.")
        sources = result.get("sources", [])
    except Exception as e:
        logger.warning("lineage narrative recall failed: %s", e)
        narrative, sources = "(semantic narrative unavailable)", []

    return {
        "run_id": run_id,
        "config_chain": chain,          # deterministic, from the index
        "lineage": narrative,           # semantic narrative, from cognee.recall
        "sources": sources,
    }


# ---------------------------------------------------------------------------
# POST /improve
# ---------------------------------------------------------------------------

@app.post("/improve", response_model=ImproveResponse, tags=["Core"])
async def improve(req: ImproveRequest):
    """
    Trigger Cognee's graph enrichment (cognify) on a dataset.

    Can be called manually or is triggered automatically after every N runs.
    """
    from memory import improve_memory
    try:
        result = await improve_memory(dataset_name=req.dataset_name)
        return ImproveResponse(**result)
    except Exception as e:
        logger.exception("improve_memory() failed")
        _error(500, "improve_failed", str(e))


# ---------------------------------------------------------------------------
# POST /forget
# ---------------------------------------------------------------------------

@app.post("/forget", response_model=ForgetResponse, tags=["Core"])
async def forget(req: ForgetRequest):
    """
    Remove stale data from a dataset.

    criteria examples:
      {"delete_dataset": true}                    — forget entire dataset
      {"status": "aborted"}                        — forget aborted runs
      {"max_wall_clock_seconds": 60}               — forget very short runs
    """
    from memory import forget_stale
    try:
        result = await forget_stale(req.dataset_name, req.criteria)
        return ForgetResponse(**result)
    except Exception as e:
        logger.exception("forget_stale() failed")
        _error(500, "forget_failed", str(e))


# ---------------------------------------------------------------------------
# POST /promote
# ---------------------------------------------------------------------------

@app.post("/promote", response_model=PromoteResponse, tags=["Core"])
async def promote(req: PromoteRequest):
    """
    Promote exploratory memory into the shared graph.

    Native path only: pass the session_id from a prior POST /remember call
    made with session_id set. That session is bridged into to_dataset natively
    via cognee.improve(session_ids=[...]).
    """
    from memory import promote_to_shared
    try:
        result = await promote_to_shared(req.to_dataset, session_id=req.session_id)
        return PromoteResponse(**result)
    except Exception as e:
        logger.exception("promote_to_shared() failed")
        _error(500, "promote_failed", str(e))


# ---------------------------------------------------------------------------
# GET /orphans
# ---------------------------------------------------------------------------

@app.get("/orphans", response_model=OrphansResponse, tags=["Artifacts"])
async def orphans():
    """
    Return two lists:
    1. Files on disk with no matching Artifact node (untracked_files)
    2. Artifact nodes whose file_path no longer exists on disk (broken_references)

    Includes total size in bytes for each list — useful for "X MB of untracked files" demo beat.
    """
    import run_index
    watch_dir = os.path.abspath(os.getenv("WATCHED_DIR", "./watched_runs"))
    os.makedirs(watch_dir, exist_ok=True)

    # Known artifacts come from the persistent index (survives restart) merged
    # with anything registered this process lifetime.
    indexed = {a["file_path"]: a for a in run_index.list_artifacts()}
    for fpath, info in _artifact_registry.items():
        indexed.setdefault(fpath, {"file_path": fpath, **info})
    known_paths = set(indexed.keys())

    # Walk disk to find untracked files
    untracked: List[ArtifactInfo] = []
    for root, _dirs, files in os.walk(watch_dir):
        for fname in files:
            fpath = os.path.abspath(os.path.join(root, fname))
            if fpath not in known_paths:
                size = 0
                try:
                    size = os.path.getsize(fpath)
                except OSError:
                    pass
                untracked.append(ArtifactInfo(
                    file_path=fpath,
                    size_bytes=size,
                    artifact_type=_infer_artifact_type(fpath),
                    result_id=None,
                ))

    # Find broken references (indexed but no longer on disk)
    broken: List[ArtifactInfo] = []
    for fpath, info in indexed.items():
        if not os.path.exists(fpath):
            broken.append(ArtifactInfo(
                file_path=fpath,
                size_bytes=0,  # file is gone, no size
                artifact_type=info.get("artifact_type", "other"),
                result_id=info.get("result_id"),
            ))

    total_untracked = sum(a.size_bytes for a in untracked)
    total_broken = sum(a.size_bytes for a in broken)

    return OrphansResponse(
        untracked_files=untracked,
        broken_references=broken,
        total_untracked_size_bytes=total_untracked,
        total_broken_size_bytes=total_broken,
        untracked_count=len(untracked),
        broken_count=len(broken),
    )


# ---------------------------------------------------------------------------
# GET /health
# ---------------------------------------------------------------------------

@app.get("/health", response_model=HealthResponse, tags=["Meta"])
async def health():
    """
    Server health check. Returns Cognee version and storage backend info.
    """
    try:
        cognee_version = getattr(cognee, "__version__", "unknown")
    except Exception:
        cognee_version = "unknown"

    return HealthResponse(
        status="ok",
        cognee_version=cognee_version,
        storage_backend="SQLite (relational) + Kuzu (graph)",
        llm_provider=f"{_CONFIG.get('llm_provider_alias', '?')} ({_CONFIG.get('llm_model', '?')})"
        + ("" if _CONFIG.get("llm_key_present") else " [NO KEY]"),
        embedding_provider=f"{_CONFIG.get('embedding_provider', '?')}/{_CONFIG.get('embedding_model', '?')}",
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn
    host = os.getenv("HOST", "0.0.0.0")
    # Default changed from 8000 -> 8010: backend/app/main.py (the Postgres app
    # layer the frontend/MCP talk to) also defaults to 8000. Both processes
    # need to run side by side — backend/app calls this server over HTTP for
    # the memory-backed endpoints (see backend/app/cognee_client.py).
    port = int(os.getenv("PORT", "8010"))
    uvicorn.run("main:app", host=host, port=port, reload=False, log_level="info")
