"""
main.py — Groundhog REST API Server (FastAPI)

This is the ONLY process that imports and calls cognee directly (via memory.py).
All other services (dashboard, MCP server) must call these HTTP endpoints.

Endpoints:
  POST   /remember              Ingest a run
  POST   /check-config          Pre-flight Guard
  POST   /query                 Free-form memory query
  GET    /find-file             Artifact lookup by description
  GET    /lineage/{run_id}      Full decision/config chain for a run
  POST   /improve               Trigger graph enrichment
  POST   /forget                Remove stale data
  POST   /promote               Promote node to shared dataset
  GET    /orphans               Untracked files + broken artifact references
  GET    /health                Server + Cognee health check

OpenAPI schema: GET /openapi.json  (auto-generated by FastAPI)
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Optional

import cognee
from cognee import search, SearchType
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

load_dotenv()

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("groundhog.api")

# ---------------------------------------------------------------------------
# Cognee configuration (must happen before any cognee call)
# ---------------------------------------------------------------------------

def _configure_cognee():
    """Set Cognee LLM + embedding provider from environment variables."""
    llm_provider = os.getenv("LLM_PROVIDER", "gemini")
    llm_model = os.getenv("LLM_MODEL", "gemini/gemini-2.0-flash")
    llm_api_key = os.getenv("LLM_API_KEY", "")

    emb_provider = os.getenv("EMBEDDING_PROVIDER", "gemini")
    emb_model = os.getenv("EMBEDDING_MODEL", "gemini/gemini-embedding-001")
    emb_api_key = os.getenv("EMBEDDING_API_KEY", "")
    emb_dimensions = int(os.getenv("EMBEDDING_DIMENSIONS", "768"))

    cognee.config.llm_config = {
        "provider": llm_provider,
        "model": llm_model,
        "api_key": llm_api_key,
    }
    cognee.config.vector_db_config = {
        "embedding_provider": emb_provider,
        "embedding_model": emb_model,
        "embedding_api_key": emb_api_key,
        "embedding_dimensions": emb_dimensions,
    }
    logger.info("Cognee configured: LLM=%s/%s  Embeddings=%s/%s",
                llm_provider, llm_model, emb_provider, emb_model)


# ---------------------------------------------------------------------------
# Run counter for auto-improve trigger
# ---------------------------------------------------------------------------
_run_counter = 0
IMPROVE_EVERY_N = int(os.getenv("IMPROVE_EVERY_N_RUNS", "10"))

# ---------------------------------------------------------------------------
# Artifact registry (in-memory, populated by remember_run calls)
# ---------------------------------------------------------------------------
# Maps file_path -> {"result_id": ..., "artifact_type": ..., "description": ...}
_artifact_registry: Dict[str, Dict[str, Any]] = {}


# ---------------------------------------------------------------------------
# Lifespan (startup / shutdown)
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Configure Cognee and start file watcher on startup; clean up on shutdown."""
    _configure_cognee()
    # Initialize Cognee (creates SQLite + Kuzu DBs if not present)
    try:
        await cognee.prune.prune_system(metadata=False)  # non-destructive init ping
    except Exception:
        pass  # First run — no data to prune, that's fine

    # Start file watcher in background thread
    watch_dir = os.getenv("WATCHED_DIR", "./watched_runs")
    loop = asyncio.get_event_loop()
    try:
        from watcher import start_watcher
        start_watcher(watch_dir, loop, dataset_name="main_dataset")
        logger.info("File watcher started on: %s", os.path.abspath(watch_dir))
    except Exception as e:
        logger.warning("File watcher failed to start: %s", e)

    yield  # Server is running

    # Shutdown
    try:
        from watcher import stop_watcher
        stop_watcher()
    except Exception:
        pass


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Groundhog — ML Experiment Memory API",
    description=(
        "Data/memory layer for ML experiment reproducibility. "
        "Built on Cognee (graph memory) + Gemini LLM. "
        "All graph operations go through this API — no other service should import cognee directly."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# CORS — permissive for local dev (dashboard runs on different port)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Pydantic request / response models (this IS the API contract)
# ---------------------------------------------------------------------------

class RememberRequest(BaseModel):
    """Full run document for ingestion."""
    config_params: Dict[str, Any] = Field(..., description="Hyperparameter dict")
    result_metrics: Dict[str, Any] = Field(default_factory=dict, description="Metric name → value")
    status: str = Field(default="completed", description="completed | aborted | failed")
    rationale: str = Field(default="", description="Researcher's free-text note for this run")
    experiment_name: str = Field(default="unnamed", description="Experiment container name")
    experiment_description: str = Field(default="", description="What this experiment is testing")
    owner: str = Field(default="unknown", description="Researcher or team name")
    thread_name: str = Field(default="default", description="Research thread this run belongs to")
    hypothesis: str = Field(default="", description="Hypothesis being tested")
    dataset_name_label: str = Field(default="unknown", description="Human-readable dataset label")
    dataset_version: str = Field(default="v1")
    preprocessing_notes: str = Field(default="")
    split_rationale: str = Field(default="")
    quality_issues: str = Field(default="")
    gpu_hours: Optional[float] = None
    wall_clock_seconds: Optional[float] = None
    output_dir: Optional[str] = Field(default=None, description="Directory to scan for artifacts")
    git_commit: str = Field(default="unknown")
    derived_from_config_hash: Optional[str] = Field(default=None)
    dataset: str = Field(default="main_dataset", description="Cognee dataset name for storage")


class RememberResponse(BaseModel):
    node_id: str
    config_hash: str
    config_summary: str
    result_summary: str
    dataset_name: str
    artifact_paths: List[str]
    elapsed_seconds: float
    improved: bool = False


class CheckConfigRequest(BaseModel):
    config_params: Dict[str, Any] = Field(..., description="Hyperparameter dict to check")
    dataset: str = Field(default="main_dataset")


class CheckConfigResponse(BaseModel):
    already_tried: bool
    match_type: str = Field(..., description="exact | similar | none")
    config_hash: str
    prior_result: Optional[Dict[str, Any]] = None
    similarity_score: Optional[float] = None


class QueryRequest(BaseModel):
    question: str = Field(..., description="Natural language question")
    dataset: Optional[str] = Field(default=None, description="Restrict to this dataset or None for all")


class QueryResponse(BaseModel):
    answer: str
    sources: List[str]
    result_count: int
    dataset: Optional[str] = None


class FindFileResponse(BaseModel):
    file_path: str
    artifact_id: str
    exists_on_disk: bool
    description: str
    artifact_type: str


class ImproveRequest(BaseModel):
    dataset_name: str = Field(default="main_dataset")


class ImproveResponse(BaseModel):
    status: str
    dataset: str
    message: Optional[str] = None
    error: Optional[str] = None


class ForgetRequest(BaseModel):
    dataset_name: str
    criteria: Dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Keys: delete_dataset (bool), status (str), max_wall_clock_seconds (float)"
        ),
    )


class ForgetResponse(BaseModel):
    status: str
    dataset: str
    deleted_count: int
    criteria: Dict[str, Any]
    note: Optional[str] = None
    error: Optional[str] = None


class PromoteRequest(BaseModel):
    node_id: str
    from_dataset: str
    to_dataset: str = Field(default="main_dataset")


class PromoteResponse(BaseModel):
    status: str
    node_id: str
    from_dataset: str
    to_dataset: str
    new_node_id: Optional[str] = None
    error: Optional[str] = None


class ArtifactInfo(BaseModel):
    file_path: str
    size_bytes: int
    artifact_type: str
    result_id: Optional[str] = None


class OrphansResponse(BaseModel):
    untracked_files: List[ArtifactInfo]
    broken_references: List[ArtifactInfo]
    total_untracked_size_bytes: int
    total_broken_size_bytes: int
    untracked_count: int
    broken_count: int


class HealthResponse(BaseModel):
    status: str
    cognee_version: str
    storage_backend: str
    llm_provider: str
    embedding_provider: str


class ErrorResponse(BaseModel):
    error: str
    detail: str


# ---------------------------------------------------------------------------
# Helper — structured error
# ---------------------------------------------------------------------------

def _error(status_code: int, error: str, detail: str):
    raise HTTPException(
        status_code=status_code,
        detail={"error": error, "detail": detail},
    )


# ---------------------------------------------------------------------------
# POST /remember
# ---------------------------------------------------------------------------

@app.post("/remember", response_model=RememberResponse, tags=["Core"])
async def remember(req: RememberRequest):
    """
    Ingest a full ML run document into the memory graph.

    Returns node IDs and config_hash immediately so the caller can build
    lineage links without another round-trip.
    """
    global _run_counter

    from memory import remember_run, scan_and_register_artifacts

    try:
        run_data = req.model_dump(exclude={"dataset"})
        result = await remember_run(run_data, dataset_name=req.dataset)

        # Register artifacts in in-memory registry
        for fpath in result.get("artifact_paths", []):
            _artifact_registry[fpath] = {
                "result_id": result["node_id"],
                "artifact_type": _infer_artifact_type(fpath),
                "description": f"Auto-indexed artifact from run {result['node_id'][:12]}",
                "exists_on_disk": os.path.exists(fpath),
            }

        _run_counter += 1
        improved = False
        if _run_counter % IMPROVE_EVERY_N == 0:
            logger.info("Auto-triggering improve_memory (run_counter=%d)", _run_counter)
            asyncio.create_task(_auto_improve(req.dataset))
            improved = True

        return RememberResponse(**result, improved=improved)
    except Exception as e:
        logger.exception("remember() failed")
        _error(500, "ingestion_failed", str(e))


async def _auto_improve(dataset_name: str):
    from memory import improve_memory
    try:
        await improve_memory(dataset_name)
        logger.info("Auto-improve completed for dataset=%s", dataset_name)
    except Exception as e:
        logger.error("Auto-improve failed: %s", e)


def _infer_artifact_type(path: str) -> str:
    ext = os.path.splitext(path)[1].lower()
    mapping = {
        ".pt": "checkpoint", ".pth": "checkpoint", ".ckpt": "checkpoint",
        ".png": "plot", ".jpg": "plot", ".pdf": "plot", ".svg": "plot",
        ".log": "log", ".txt": "log",
        ".json": "eval_report", ".csv": "eval_report",
    }
    return mapping.get(ext, "other")


# ---------------------------------------------------------------------------
# POST /check-config
# ---------------------------------------------------------------------------

@app.post("/check-config", response_model=CheckConfigResponse, tags=["Core"])
async def check_config(req: CheckConfigRequest):
    """
    Pre-flight Guard: has this exact config been tried before?

    Returns exact hash match or semantic similarity match, plus prior result.
    Use this before launching a training run to avoid wasted compute.
    """
    from memory import check_config as _check_config
    try:
        result = await _check_config(req.config_params, dataset_name=req.dataset)
        return CheckConfigResponse(**result)
    except Exception as e:
        logger.exception("check_config() failed")
        _error(500, "check_config_failed", str(e))


# ---------------------------------------------------------------------------
# POST /query
# ---------------------------------------------------------------------------

@app.post("/query", response_model=QueryResponse, tags=["Core"])
async def query(req: QueryRequest):
    """
    Free-form natural language query against the memory graph.

    Works for positive AND negative results — ask "which runs failed?" and
    the graph will surface failed run nodes.
    """
    from memory import query_memory
    try:
        result = await query_memory(req.question, dataset_name=req.dataset)
        return QueryResponse(**result)
    except Exception as e:
        logger.exception("query_memory() failed")
        _error(500, "query_failed", str(e))


# ---------------------------------------------------------------------------
# GET /find-file
# ---------------------------------------------------------------------------

@app.get("/find-file", response_model=FindFileResponse, tags=["Artifacts"])
async def find_file(description: str = Query(..., description="Text description of the artifact to find")):
    """
    Find an artifact file by semantic description.

    Searches the registered artifact registry and the memory graph.
    Returns the file path, artifact ID, and whether the file still exists.
    """
    # First check in-memory registry with token overlap
    from memory import _rough_similarity
    best_score = 0.0
    best_fpath = None
    for fpath, info in _artifact_registry.items():
        score = _rough_similarity(description, info.get("description", ""))
        if score > best_score:
            best_score = score
            best_fpath = fpath

    if best_fpath and best_score > 0.1:
        info = _artifact_registry[best_fpath]
        return FindFileResponse(
            file_path=best_fpath,
            artifact_id=best_fpath,
            exists_on_disk=os.path.exists(best_fpath),
            description=info.get("description", ""),
            artifact_type=info.get("artifact_type", "other"),
        )

    # Fall back to graph query
    from memory import query_memory
    result = await query_memory(f"Find artifact file: {description}")
    if result.get("sources"):
        src = result["sources"][0]
        return FindFileResponse(
            file_path=str(src),
            artifact_id=str(src),
            exists_on_disk=os.path.exists(str(src)),
            description=result.get("answer", "")[:200],
            artifact_type="other",
        )

    raise HTTPException(
        status_code=404,
        detail={"error": "artifact_not_found", "detail": f"No artifact matching: {description}"},
    )


# ---------------------------------------------------------------------------
# GET /lineage/{run_id}
# ---------------------------------------------------------------------------

@app.get("/lineage/{run_id}", tags=["Provenance"])
async def lineage(run_id: str):
    """
    Return the full decision / hypothesis / config chain for a run.

    run_id can be a config_hash or any node ID returned by /remember.
    """
    from memory import query_memory
    try:
        result = await query_memory(
            f"What is the full lineage, decision chain, and config history for run {run_id}?"
        )
        return {
            "run_id": run_id,
            "lineage": result.get("answer", "No lineage found."),
            "sources": result.get("sources", []),
        }
    except Exception as e:
        logger.exception("lineage() failed")
        _error(500, "lineage_failed", str(e))


# ---------------------------------------------------------------------------
# POST /improve
# ---------------------------------------------------------------------------

@app.post("/improve", response_model=ImproveResponse, tags=["Core"])
async def improve(req: ImproveRequest):
    """
    Trigger Cognee's graph enrichment (cognify) on a dataset.

    Can be called manually or is triggered automatically after every N runs.
    """
    from memory import improve_memory
    try:
        result = await improve_memory(dataset_name=req.dataset_name)
        return ImproveResponse(**result)
    except Exception as e:
        logger.exception("improve_memory() failed")
        _error(500, "improve_failed", str(e))


# ---------------------------------------------------------------------------
# POST /forget
# ---------------------------------------------------------------------------

@app.post("/forget", response_model=ForgetResponse, tags=["Core"])
async def forget(req: ForgetRequest):
    """
    Remove stale data from a dataset.

    criteria examples:
      {"delete_dataset": true}                    — forget entire dataset
      {"status": "aborted"}                        — forget aborted runs
      {"max_wall_clock_seconds": 60}               — forget very short runs
    """
    from memory import forget_stale
    try:
        result = await forget_stale(req.dataset_name, req.criteria)
        return ForgetResponse(**result)
    except Exception as e:
        logger.exception("forget_stale() failed")
        _error(500, "forget_failed", str(e))


# ---------------------------------------------------------------------------
# POST /promote
# ---------------------------------------------------------------------------

@app.post("/promote", response_model=PromoteResponse, tags=["Core"])
async def promote(req: PromoteRequest):
    """
    Promote a node from a private/exploratory dataset into the shared dataset.

    The original node is kept with a promoted=True flag; the content is
    re-ingested into the target dataset for team-wide access.
    """
    from memory import promote_to_shared
    try:
        result = await promote_to_shared(req.node_id, req.from_dataset, req.to_dataset)
        return PromoteResponse(**result)
    except Exception as e:
        logger.exception("promote_to_shared() failed")
        _error(500, "promote_failed", str(e))


# ---------------------------------------------------------------------------
# GET /orphans
# ---------------------------------------------------------------------------

@app.get("/orphans", response_model=OrphansResponse, tags=["Artifacts"])
async def orphans():
    """
    Return two lists:
    1. Files on disk with no matching Artifact node (untracked_files)
    2. Artifact nodes whose file_path no longer exists on disk (broken_references)

    Includes total size in bytes for each list — useful for "X MB of untracked files" demo beat.
    """
    watch_dir = os.path.abspath(os.getenv("WATCHED_DIR", "./watched_runs"))
    os.makedirs(watch_dir, exist_ok=True)

    known_paths = set(_artifact_registry.keys())

    # Walk disk to find untracked files
    untracked: List[ArtifactInfo] = []
    for root, _dirs, files in os.walk(watch_dir):
        for fname in files:
            fpath = os.path.abspath(os.path.join(root, fname))
            if fpath not in known_paths:
                size = 0
                try:
                    size = os.path.getsize(fpath)
                except OSError:
                    pass
                untracked.append(ArtifactInfo(
                    file_path=fpath,
                    size_bytes=size,
                    artifact_type=_infer_artifact_type(fpath),
                    result_id=None,
                ))

    # Find broken references (registered but no longer on disk)
    broken: List[ArtifactInfo] = []
    for fpath, info in _artifact_registry.items():
        if not os.path.exists(fpath):
            broken.append(ArtifactInfo(
                file_path=fpath,
                size_bytes=0,  # file is gone, no size
                artifact_type=info.get("artifact_type", "other"),
                result_id=info.get("result_id"),
            ))

    total_untracked = sum(a.size_bytes for a in untracked)
    total_broken = sum(a.size_bytes for a in broken)

    return OrphansResponse(
        untracked_files=untracked,
        broken_references=broken,
        total_untracked_size_bytes=total_untracked,
        total_broken_size_bytes=total_broken,
        untracked_count=len(untracked),
        broken_count=len(broken),
    )


# ---------------------------------------------------------------------------
# GET /health
# ---------------------------------------------------------------------------

@app.get("/health", response_model=HealthResponse, tags=["Meta"])
async def health():
    """
    Server health check. Returns Cognee version and storage backend info.
    """
    try:
        cognee_version = getattr(cognee, "__version__", "unknown")
    except Exception:
        cognee_version = "unknown"

    return HealthResponse(
        status="ok",
        cognee_version=cognee_version,
        storage_backend="SQLite (relational) + Kuzu (graph)",
        llm_provider=os.getenv("LLM_PROVIDER", "gemini"),
        embedding_provider=os.getenv("EMBEDDING_PROVIDER", "gemini"),
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn
    host = os.getenv("HOST", "0.0.0.0")
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run("main:app", host=host, port=port, reload=False, log_level="info")
